name: demo-warning-failure

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step échoue avec warning
        run: |
          echo "::warning::Un problème est détecté"
          exit 1