name: Deploy Project roadmap
on:
  workflow_dispatch:

jobs:
  validate-and-deploy-plan:
    name: Validate & Deploy Roadmap To GitHub Issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v3

      - name: Run The Plan Validation Script
        run: uv run 

      - name: Run Deployment Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/seed.py
