name: Deploy Project roadmap
on:
  workflow_dispatch:

jobs:
  validate-and-deploy-plan:
    name: Validate & Deploy Roadmap To GitHub Issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    env:
      PLAN: '_roadmap/roadmap_plan.json'
      LOCK_FILE: '_roadmap/.roadmap_activated'
      PLAN_CHECKER: '_roadmap/validate_plan.py'
      PLAN_DEPLOYER: '_roadmap/deploy_plan.py'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v3

      # - name: Install Python runtime (3.14)
      #   run: uv python install 3.14

      # - name: Install Pydantic (v2.12.x)
      #   run: uv add 'pydantic>=2.12,<2.13'

      - name: Validate Project Plan
        id: validate
        run: |
          uv run \
              --no-project \
              --python 3.14 \
              --with "pydantic>=2.12,<2.13" \
              "$PLAN_CHECKER" --plan "$PLAN" --marker "$LOCK_FILE"

      # - name: Deploy GitHub Issues
      #   if: steps.validate.outputs.run_deploy == 'true'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: uv run "$PLAN_DEPLOYER" --plan "$PLAN" --marker "$LOCK_FILE"
