name: demo-warning-success

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step avec warning
        run: |
          echo "::warning::Ceci est un avertissement"
          echo "Le step réussit quand même"